environment: development
debug: true
testing: false

# Core settings
max_workers: 8
batch_size: 1000
request_timeout: 30

# Cache settings
cache:
  memory_size: 10000
  disk_size: 1000000
  disk_path: cache
  ttl: 3600
  policy: lru

# Logging settings
logging:
  level: INFO
  format: "%(levelname)-8s | %(name)s | %(message)s"
  file_path: logs/tenire.log
  max_size: 10485760
  backup_count: 5

# Betting settings
betting:
  default_amount: 1.0
  min_amount: 0.1
  max_amount: 100.0
  cooldown_minutes: 1
  daily_limit: 1000.0
  session_limit: 500.0

# ChatGPT settings
chatgpt:
  api_key: ${TENIRE_CHATGPT_API_KEY}
  model: gpt-04
  temperature: 0.025
  max_tokens: 1000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  max_context_length: 10000
  max_concurrent_requests: 5

# Stake settings
stake:
  username: ${TENIRE_STAKE_USERNAME}
  password: ${TENIRE_STAKE_PASSWORD}

# GUI settings
gui:
  sidebar_width: 400
  update_interval: 100
  max_messages: 1000
  theme: dark 